apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-web
  namespace: argocd
spec:
  project: default
  source:
    chart: nginx               # The name of the chart
    repoURL: https://charts.bitnami.com/bitnami # The official Helm registry
    targetRevision: 18.2.1     # Locks the chart version for stability
    helm:
      parameters:
        - name: replicaCount
          value: "1"           # Overrides the default replicas right here!
        - name: service.type
          value: NodePort      # Changes the service from ClusterIP to NodePort
        - name: service.nodePorts.http
          value: "30081"       # Sets a static port to access on Minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true